# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ZhouDao_NetWorkManger' do

end

target 'ZhouDao_NetWorkMangerTests' do

end

target 'ZhouDao_NetWorkMangerUITests' do

end

pod 'AFNetworking', '~> 3.1.0'

