platform:ios, '7.0'
pod 'SDWebImage', '~> 3.8.2'
pod 'AFNetworking', '~> 3.1.0'
#键盘控制
#pod 'IQKeyboardManager', '~> 3.3.4'
pod 'IQKeyboardManager', '~> 3.3.7'
#轮播图
pod 'SDCycleScrollView', '~> 1.65'
#友盟分享
#pod ‘UMengUShare/UI’
pod ‘UMengUShare/Social/Sina'
pod ‘UMengUShare/Social/WeChat'
pod ‘UMengUShare/Social/QQ'
#友盟应用统计 无广告标识符
pod 'UMengAnalytics-NO-IDFA', '~> 4.1.3'
pod 'LCActionSheet', '~> 1.2.3'
 #百度地图SDK
#pod 'BaiduMapKit'
#高德地图
#pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
pod 'AMapNavi-NO-IDFA', '~> 2.3.0'                 #导航SDK
pod 'AMapLocation-NO-IDFA', '~> 2.1.1'             #定位SDK
pod 'AMapSearch-NO-IDFA', '~> 4.3.0'               #搜索服务SDK
#tabbar
pod 'CYLTabBarController', '~> 1.5.6'     #TabBar1.2.1
pod 'pop', '~> 1.0.9'
#置顶
pod 'SWTableViewCell', '~> 0.3.7'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'QiniuUpload', '~> 2.0.2'
#滑动返回
pod 'FDFullscreenPopGesture', '1.1'
pod 'WebViewJavascriptBridge', '~> 5.0.5'
#检测更新
pod 'Harpy'


#菜单
#pod 'DLWidgetMenu'
#pod 'FMDB', '~> 2.6.2'

#webView
#pod 'DZNWebViewController'
#pod 'MJExtension', '~> 3.0.10'
#错误日志
#pod 'Bugly', '~> 2.3.1'
#掉帧测试
#pod 'KMCGeigerCounter', '~> 0.2.2'
#pod 'XHRealTimeBlur'
#下载
#pod 'WHCNetWorkKit', '~> 0.0.3'
#七牛
#pod 'Qiniu', '~> 7.0.16'
#pod 'FMDB', '~> 2.6'
#夜间模式
#pod 'DKNightVersion', '~> 1.4'
#pod 'TAPageControl'


