# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SwiftControls' do

pod 'Alamofire', '~> 4.0.1'

end

target 'SwiftControlsTests' do

end

target 'SwiftControlsUITests' do

end

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.2'
